image: "registry.gitlab.com/connorshea/videogamelist:latest"

services:
  - postgres:11

variables:
  BUNDLE_PATH: vendor/bundle
  DB_HOST: postgres
  POSTGRES_DB: ci_test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  RAILS_ENV: test
  RACK_ENV: test
  NODE_ENV: test
  CI: 'true'
  BUNDLER_VERSION: '2.0.2'

# Cache gems and node_modules in between builds
cache:
  key: '$BUNDLER_VERSION'
  paths:
    - vendor/bundle
    - node_modules
  # By default, only pull. We don't need every job to update the cache.
  policy: pull

before_script:
  - ruby -v
  - gem install bundler:$BUNDLER_VERSION
  - bundle install -j $(nproc)
  - yarn install --frozen-lockfile
  - cp config/database.yml.ci config/database.yml
  - bundle exec rails db:create
  - bundle exec rails db:migrate --trace

.no_db_template:
  before_script: &no_db_necessary
    - ruby -v
    - gem install bundler:$BUNDLER_VERSION
    - bundle install -j $(nproc)
    - yarn install --frozen-lockfile

# A simple hack to make it so the package cache is updated independently of any
# other jobs, to prevent unnecessary time spent pushing the cache for more than
# one job.
cacher:
  before_script: *no_db_necessary
  script:
    - bundle clean --force
  cache:
    policy: pull-push

sorbet:tc:
  before_script: *no_db_necessary
  script:
    - bundle exec srb tc . --ignore=vendor/

typescript:tsc:
  before_script: *no_db_necessary
  script:
    - yarn run tsc

rubocop:
  before_script: *no_db_necessary
  script:
    - bundle exec rubocop

factory_bot_lint:
  script:
    - bundle exec rake factory_bot:lint

rspec:
  script:
    - bundle exec rspec
  coverage: '/\(\d+.\d+\%\) covered/'

db:seed:
  script:
    - bundle exec rails db:seed

graphql:lint:
  script:
    - bundle exec rake graphql:schema:idl
    - yarn graphql-schema-linter schema.graphql
