inherit_from: .rubocop_todo.yml

Style/Lambda:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/AlignHash:
  Enabled: false
