require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/bundle/**/*"
    - "sorbet/**/*"

###################### Bundler #############################

Bundler/OrderedGems:
  Enabled: false

###################### Layout ##############################

Layout/AlignArguments:
  Enabled: false

#################### Metrics ###############################

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

#################### Rails #################################

# By default, the rails cops are not run. Override in project or home
# directory .rubocop.yml files, or by giving the -R/--rails option.
Rails:
  Enabled: true

# TODO: Enable this.
Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

# TODO: Enable this?
Rails/NotNullColumn:
  Enabled: false

Rails/Output:
  Enabled: true
  Exclude:
    - "db/seeds.rb"
    - "db/seeds/*.rb"
    - "lib/wikidata_helper.rb"

Rails/RequestReferer:
  Enabled: true
  EnforcedStyle: referrer

Rails/HelperInstanceVariable:
  Enabled: true
  Exclude:
    - 'app/helpers/settings_helper.rb'

# This cop is buggy.
Rails/BulkChangeTable:
  Enabled: false

#################### Style ###############################

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - 'spec/requests/**/*_spec.rb'

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/Next:
  Enabled: true
  Exclude:
    - "lib/tasks/import/wikidata_import_games.rake"

Style/NumericLiterals:
  Enabled: true
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*.rb"

Style/NumericPredicate:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/WordArray:
  Enabled: false

#################### RSpec ###############################

RSpec/ExampleLength:
  Enabled: false

RSpec/HookArgument:
  Enabled: true
  EnforcedStyle: each

RSpec/ImplicitExpect:
  Enabled: true
  EnforcedStyle: 'should'

RSpec/MultipleExpectations:
  Enabled: true
  Max: 3

RSpec/DescribedClass:
  Enabled: false

RSpec/EmptyLineAfterExample:
  Enabled: false
