notifications:
  email: false
language: ruby
rvm:
  - 2.6
services:
  - postgresql
addons:
  chrome: stable
env:
  - TRAVIS_NODE_VERSION="9" CI=true RAILS_ENV=test
cache:
  directories:
    - vendor/bundle
    - /home/travis/.rvm/
    - node_modules
install:
  - gem install bundler
  - bundle install --jobs 3 --retry 3
  - nvm install 9
  - nvm use 9
  - yarn install --frozen-lockfile
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rubocop
  - bundle exec rake db:migrate --trace
  - bundle exec rake factory_bot:lint
  - bundle exec rake spec

