version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    # The prod.env file will need DATABASE_URL, DATABASE_PASSWORD,
    # and SECRET_KEY_BASE.
    env_file:
      - prod.env
    environment:
      VGLIST_DATABASE_HOST: db
    depends_on:
      - db
