version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      VGLIST_DATABASE_HOST: db
      DATABASE_URL: postgres://postgres@db
      DATABASE_PASSWORD: 'productionpassword'
    depends_on:
      - db
