version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    version_requirement_updates: "auto"
    default_assignees:
      - "connorshea"
    # Automerge minor-level updates automatically (if tests pass).
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
      - match:
          dependency_type: "production"
          update_type: "semver:minor"
    # Allow all direct and indirect dependencies to be updated.
    allowed_updates:
      - match:
          update_type: "all"
    # These AWS and Sorbet gems are updated too often, so we skip them to avoid obnoxious PRs.
    ignored_updates:
      - match:
          dependency_name: "aws-sdk-core"
      - match:
          dependency_name: "aws-partitions"
      - match:
          dependency_name: "aws-sdk-kms"
      - match:
          dependency_name: "aws-sdk-s3"
      - match:
          dependency_name: "sorbet"
      - match:
          dependency_name: "sorbet-runtime"

  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"
    version_requirement_updates: "auto"
    default_assignees:
      - "connorshea"
    # Allow all direct dependencies to be updated, only allow indirect
    # dependencies to update when there's a security release.
    allowed_updates:
      - match:
          update_type: all
          dependency_type: direct
      - match:
          update_type: security
          dependency_type: indirect
    # Disallow updates past 4.x for webpack and 3.x for webpack-dev-server.
    # Webpacker 4.x only supports webpack 4.x.
    ignored_updates:
      - match:
          dependency_name: "webpack"
          version_requirement: "5.x"
      - match:
          dependency_name: "webpack-dev-server"
          version_requirement: "4.x"

  # Checks for Dockerfile updates weekly.
  # Dependabot will automatically detect any files with "Dockerfile" in the name.
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"
    default_assignees:
      - "connorshea"
